# Práctica 2
K-means
    Elegir instacias del dataset como centroides iniciales
    Distirbuir puntos del dataset a los centroides
    Calcular la media de las distancias respecto de los puntos
    Se recalculaba el centroide 
    Repetir hasta que no haya cambios
    
Estaría bien usar la misma interfaz que sckikit learn
Kmeans = Kmeans(K=5)
Kmeans.fit(X)
Kmeans.predict(X)

Tenemos un conjunto de datos, eliges el numero de clusters (n_clusters), asignas los centroides a unos datos aleatoriamente (init -> puntos aleatorios del dataset), y después asignas los datos a los clusters (asignar_clusters). Después hay que computar los nuevos centroides en un bucle y volver a asignar los clusters hasta que se cumpla la condición de parada.

In [2]:
# con la librería de SciKit Learn:
import sklearn
import sklearn.cluster 
import KMeans

kmeans = KMeans()
kmeans.fit(X)
kmeans.predict(X)

ModuleNotFoundError: No module named 'skelarn'

In [6]:
import pandas as pd
stars = pd.read_csv('Stars2.csv')

In [9]:
stars.shape
len(stars)

240

In [3]:
stars.head()

Temperature         L       R    A_M Color Spectral_Class
0         3068  0.002400  0.1700  16.12   Red              M
1         3042  0.000500  0.1542  16.60   Red              M
2         2600  0.000300  0.1020  18.70   Red              M
3         2800  0.000200  0.1600  16.65   Red              M
4         1939  0.000138  0.1030  20.06   Red              M

In [8]:
import numpy as np
import math
from math import dist

In [9]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [7]:
 
 print(np.random.choice(list(range(0, len(stars))), size = 5, replace = False))

[100 203  89 138 222]


In [ ]:
class KMeans_Ours():
    def __init__(self, n_clusters=8, max_iter=300, random_state=55):
        self.n_clusters = k
        self.max_iter = max_iter
        self.iter = 0
        self.random_state = random_state
        
        self.X= []
        
        self._centroids= []
        self._inertia=[]
        self._labels=[]
        self.history = []
    
    def fit(self, X):
        """Este método entrena el modelo con el dataset proporcionado, aplicando el algoritmo de asignación de centroides"""
        self.X = X
        self._assign_centroids()
        self._assign_labels()
        
        while not self._stop: # si se llega a max iter o si centroides no cambian (con último valor de self.history), una u otra
            self._add_history_step() 
            # con esto podemos hacer un gráfico (no se pide pero quedaría rechulón)
            
            self._update_centroides()
            self._assign_labels()
            
            self.iter += 1
            
        
        ###algoritmo: asignar centroides....
    
    def predict(self, X):
        # contemplar posibilidad de triangulación
        pass
    
    def _assign_centroids(self):
        # utilizar el módulo random de numpy para asignar los centroides: check
        # sólo para la primera iteración (asignación de centroides iniciales): check
        # un centroide a la misma posición dato aleatoriamente 
        # con replace = false nos aseguramos de que no se repita el mismo valor para dos centroides diferentes,
        # de forma que todos los centroides tomen coordenadas distintas
        c_index = np.random.choice(list(range(0, len(self.X))), size = self.n_clusters, replace = False)
        for i in c_index:
            self._centroids.append(self.X[i])
        # asignar valores de los datos a los que equivalen esas posiciones en la tabla a los "centroides"        
    
    def _assign_labels(self):
        # función para asignar los datos a un centroides
        # linalg.norm -> normaliza los vectores, no calcula distancias como tal; no es lo que buscamos
        self._inertia = []
        
        # generación de la matriz
        for i in range(len(self.X)):
            self._inertia.append(self._compute_inertia(self.X[i]))
        
        # encasillamiento con labels de cada dato a su respectivo centroide 
        
        for i in range(len(matriz_distancias)):
            self._labels.append(np.argmin(matriz_distancias[i], axis = 0))

    
    def _stop(self):
        """ condición de parada del bucle de actualizaciónd e labels y centroides de función fit() """
        if self.iter == self.max_iter: 
                return True
        prev_centroids= self.history[-1]['centroids']
        for i in range (self.n_clusters):
            #Si ha cambiado algún centroide el algoritmo continúa
            if self._centroids[i] != prev_centroids [i]:
                return False
        #Si no hay diferencias los centroides no han cambiado en la última iteración y se cumple la condición de parada.    
        return True
    
    def _update_centroides(self):
        # siguientes iteraciones para reposicionar los centroides
    
        for i in range(len(self.n_centroids)):
            self._centroids.append (X[labels_==self._centroids[i]].mean(axis = 0))
    
    def _compute_inertia(self, x):
        """ distancia entre el punto 'x' y cada centroide' """
        distance_row=[]
        for centroid in self._centroids: 
            distance_row.append(dist(x,centroid))
       
        return distance_row
        
    def _add_history_step(self):
        """ actualización de historial de centroides para nueva iteración """
        self.history.append(
            {   'iteration': self.iter,
                'centroids':  self._centroids,  
                'labels' : self._labels,
                'inertia':  self._inertia
            })
    

In [37]:
X = np.random.random(size = (100, 2))
centroide = np.random.random_integers(0, len(X))
centroide
len(X)

<ipython-input-37-f68aa6cb5981>:2: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  centroide = np.random.random_integers(0, len(X))


100

In [17]:
centroids = []
centroids = np.random.choice(range(0, len(X)), size = 8, replace = False)
centroids

array([24, 12, 50, 71, 13, 36, 70, 15])

In [39]:
matriz = [1, 2, [3, 4], [5, 6]]
print(matriz[0][2], matriz[2][1])

TypeError: 'int' object is not subscriptable

In [57]:
matriz_distancias = []
for i in range(len(X)):
    matriz_distancias.append([])
    for j in range(7):
         matriz_distancias[i].append(np.random.randint(1, 10))



[[5, 2, 1, 4, 3, 3, 7],
 [1, 7, 2, 8, 1, 5, 3],
 [6, 1, 5, 5, 9, 8, 6],
 [7, 3, 9, 6, 7, 8, 9],
 [9, 5, 4, 8, 1, 2, 8],
 [3, 7, 1, 2, 9, 6, 8],
 [2, 7, 9, 4, 4, 6, 7],
 [3, 8, 5, 1, 2, 5, 6],
 [3, 2, 3, 3, 3, 6, 4],
 [1, 4, 9, 3, 9, 3, 5],
 [2, 6, 7, 6, 6, 6, 1],
 [4, 2, 8, 9, 9, 5, 3],
 [8, 9, 8, 7, 2, 7, 4],
 [1, 9, 7, 9, 5, 3, 8],
 [6, 6, 2, 8, 6, 3, 9],
 [6, 1, 6, 2, 6, 5, 1],
 [8, 9, 7, 1, 7, 1, 4],
 [9, 7, 6, 1, 5, 2, 8],
 [7, 2, 5, 2, 6, 2, 5],
 [9, 8, 1, 1, 5, 5, 1],
 [7, 7, 1, 2, 7, 5, 2],
 [2, 4, 3, 7, 8, 4, 5],
 [1, 6, 5, 3, 6, 6, 1],
 [6, 8, 1, 8, 2, 6, 4],
 [9, 6, 1, 2, 7, 7, 3],
 [8, 3, 9, 9, 6, 1, 1],
 [5, 1, 6, 6, 3, 7, 5],
 [2, 3, 2, 6, 5, 9, 5],
 [2, 4, 9, 5, 3, 5, 2],
 [3, 3, 7, 7, 9, 1, 8],
 [6, 7, 6, 6, 4, 5, 2],
 [7, 7, 4, 7, 9, 7, 6],
 [7, 2, 3, 8, 1, 5, 8],
 [5, 6, 4, 9, 6, 9, 1],
 [1, 8, 6, 8, 9, 7, 5],
 [5, 7, 1, 2, 5, 7, 7],
 [4, 9, 2, 2, 5, 2, 3],
 [2, 6, 6, 1, 6, 3, 4],
 [6, 7, 1, 8, 8, 6, 6],
 [3, 5, 9, 5, 6, 7, 1],
 [2, 4, 8, 9, 8, 3, 6],
 [2, 2, 5, 3, 6,

In [72]:
labels_=[]
for i in range(len(matriz_distancias)):
    labels_.append(np.argmin(matriz_distancias[i], axis = 0))

labels_

[2,
 0,
 1,
 1,
 4,
 2,
 0,
 3,
 1,
 0,
 6,
 1,
 4,
 0,
 2,
 1,
 3,
 3,
 1,
 2,
 2,
 0,
 0,
 2,
 2,
 5,
 1,
 0,
 0,
 5,
 6,
 2,
 4,
 6,
 0,
 2,
 2,
 3,
 2,
 6,
 0,
 0,
 0,
 3,
 5,
 4,
 6,
 1,
 1,
 5,
 6,
 6,
 0,
 1,
 0,
 5,
 2,
 1,
 1,
 3,
 1,
 2,
 0,
 0,
 5,
 3,
 4,
 0,
 6,
 1,
 4,
 0,
 2,
 0,
 2,
 2,
 1,
 0,
 5,
 2,
 6,
 0,
 1,
 2,
 0,
 0,
 0,
 4,
 2,
 6,
 0,
 5,
 0,
 3,
 1,
 2,
 2,
 5,
 5,
 0]

In [30]:
np.random.randint(1, 10)

5

In [71]:
np.argmin(matriz_distancias, axis=0)

array([2, 0, 1, 1, 4, 2, 0, 3, 1, 0, 6, 1, 4, 0, 2, 1, 3, 3, 1, 2, 2, 0,
       0, 2, 2, 5, 1, 0, 0, 5, 6, 2, 4, 6, 0, 2, 2, 3, 2, 6, 0, 0, 0, 3,
       5, 4, 6, 1, 1, 5, 6, 6, 0, 1, 0, 5, 2, 1, 1, 3, 1, 2, 0, 0, 5, 3,
       4, 0, 6, 1, 4, 0, 2, 0, 2, 2, 1, 0, 5, 2, 6, 0, 1, 2, 0, 0, 0, 4,
       2, 6, 0, 5, 0, 3, 1, 2, 2, 5, 5, 0], dtype=int64)

In [26]:
kmeans = KMeans()
kmeans.fit(X)

NameError: name 'KMeans' is not defined

Scikit learn es una librería de código abierto, se puede ver cómo está implementado en Scikit learn, no copiar la misma solución, pero usarlo como inspiración. Hay un apartado de indicar similitud con scikit learn.

## PCA
Algoritmo no supervisado muy útil, reduce la dimensionalidad de los datos (columnas). En lugar de eliminar columnas, existen métodos más interesantes que ese.
Prdecir el número escrito en el gráfico en base a la luminosidad de los píxeles. Se ve bien con cmap = 'Greys'.

Se usará el algoritmo PCA antes del algoritmo de clustering, y el de clustering se usará sobre las dos dimensiones que devuelve PCA (kmeans o lo que sea)

In [ ]:
from sklearn.datasets import load_digits
import matplotlib.pylot as plt

from sklearn.decomposition import PCA

X = load.digits().data
X.shape
plt.imshow(np.reshape(X[0], (8,8)))
pca = PCA.fit(X)
plt.plot

In [ ]:
X_pca

# Pruebas fallidas...

In [ ]:
"""self.history.centroids
        
        for i in range(self.n_clusters):
            centroide = np.random.random_integers(0, len(self.X)-1, size=self.n_clusters)
            
            for c in centroide:
                if centroide.count(c) == 1:
                    self.history.centroids.append(X[c])
                else:
                    centroide[c] = np.random.random_integers(0, len(self.X)-1)
                    while centroide
            
            duplicate = False
            while self.history.centroids du
            if i>0:
                for i in range(len(self.history.centroids)):
                    if centroide == self.history.centroids[i]:
                        
            self.history.centroids.append(np.)"""